steps:
  # Step 1: Use the official .NET SDK image to build the application
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        dotnet workload restore
        dotnet publish -c Release -o ./publish
  #     dotnet workload update
  #     dotnet workload install aspire
  #     dotnet restore eShop.Web.slnf
        
  # dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj
  # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin        

  # dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj
  # Step 2: Use the official ASP.NET Core image to prepare the runtime environment
  - name: 'mcr.microsoft.com/dotnet/aspnet:8.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /app && cp -r /workspace/publish/* /app      

  # Step 3: Deploy the application to Google App Engine flexible environment
  - name: 'gcr.io/cloud-builders/gcloud'

    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'  # Assuming your app.yaml file is in the root directory
      - '--version=3'  # Optionally specify the version
      - '--project=arvut052024'  # Replace [efactory-202404] with your actual project ID
      - '--quiet'  # Optional: Suppresses all interactive prompts

timeout:
  seconds: 1600  # Set a timeout value according to your project's needs

